In [481]:
#import libraries 
import numpy as np  
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn import datasets, linear_model
from sklearn.preprocessing import StandardScaler
#from imblearn.over_sampling import RandomOverSampler 
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import RobustScaler 

In [482]:
#import data 
white_wine = pd.read_csv("wine+quality\winequality-white.csv", sep= ';', delimiter=None) 

#make a copy
ww = white_wine

In [483]:
#remove all duplicates 
ww.drop_duplicates(inplace=True)

In [484]:
#unify column names 
ww.rename(columns = {'fixed acidity':'fixed_acidity','volatile acidity':'volatile_acidity','citric acid':'citric_acid','residual sugar':'residual_sugar','free sulfur dioxide':'free_sulfur_dioxide', 'total sulfur dioxide':'total_sulfur_dioxide'}, inplace=True)

In [485]:
#add a column 
#ww.insert(12, "colour", 'white')

Next add the quality label column 

In [486]:
#add quality label column - low 1-4, medium 5-6, high 7-10 
ww['quality_label'] = ww['quality'].apply(lambda value: 'low'
if value <= 4 else 'medium'
if value <= 6 else 'high')
ww['quality_label'] = pd.Categorical(ww['quality_label'], 
categories=['low', 'medium', 'high']) 

Label Encoder 

In [487]:
ww1 = ww.copy()

In [488]:
#check unique values of this column 
ww1['quality_label'].unique()

['medium', 'high', 'low']
Categories (3, object): ['low', 'medium', 'high']

In [489]:
#first save label encoder 
lbl_enc = LabelEncoder()

#use function fit transform 
ww1['quality_label'] = lbl_enc.fit_transform(ww1['quality_label'])


In [490]:
ww['quality_label'].value_counts()

medium    2963
high       825
low        173
Name: quality_label, dtype: int64

In [491]:
ww1['quality_label'].value_counts()
# low = 1 
# medium = 2 
# high = 0 

2    2963
0     825
1     173
Name: quality_label, dtype: int64

In [492]:
#for label in ww.columns[:-1]:
    #plt.hist(ww[ww["quality_label"]==0][label], color = 'blue', label = 'High Quality', alpha = 0.7, density=True)
    #plt.hist(ww[ww["quality_label"]==1][label], color = 'red', label = 'Low Quality', alpha = 0.7, density=True)
    #plt.title(label)
    #plt.xlabel(label)
    #plt.legend()
    #plt.show()

In [493]:
X = ww1[ww1.columns[:-1]].values #calling all columns until the last one 
y = ww1[ww1.columns[-1]].values #calling only the last column 

In [494]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state=39)

In [495]:
# standard scaler
#scale data 
def scale_dataset(ww1, oversample=False):
    
    scaler = StandardScaler() # check rules here for group splitting 
    X = scaler.fit_transform(X) 

    data = np.hstack((X, np.reshape(y, (-1, 1))))
    # y is only 2D, so call numpy reshape to make it  3Dimensional Item 
    # because y is only 1 column

    return data, X, y

In [496]:
#train, X_train, y_train = scale_dataset(train)
#valid, X_valid, y_valid = scale_dataset(valid)
#test, X_test, y_test = scale_dataset(test)

In [497]:
#train data and run model 


knn_model = KNeighborsClassifier(n_neighbors=4)
knn_model.fit(X_train, y_train)

y_pred = knn_model.predict(X_test)


In [498]:
#check classification report 
print(classification_report(y_test, y_pred)) 

# low is 1 
# medium is 2 
# high is 0

              precision    recall  f1-score   support

           0       0.51      0.50      0.51       157
           1       0.35      0.16      0.22        37
           2       0.83      0.86      0.84       599

    accuracy                           0.75       793
   macro avg       0.56      0.51      0.52       793
weighted avg       0.74      0.75      0.75       793



In [499]:
print(confusion_matrix(y_test, y_pred))

[[ 79   1  77]
 [  0   6  31]
 [ 76  10 513]]
